language: r
os: linux
dist: xenial
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual

git:
  depth: 1
  
r_binary_packages:
  - pkgload
  - devtools

before_script:
  - R -e "pkgload::load_all(); devtools::document()"

jobs:
  include:
    - r: 3.5.0
    - r: release
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      r_binary_packages:
       - devtools
       - memoise
       - phangorn
       - R.cache
       - Rdpack
       - roxygen2
       - testthat
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        cleanup: false
        skip_cleanup: true
        local_dir: "docs"
        keep-history: true
        on: 
          branch: master
    - r: devel
      branches:
        only: master
      r_binary_packages:
       - covr
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      branches:
        only: master
      r: release
      before_install:
      - sudo tlmgr install doi titling hyperref
#  allow_failures:
